### ISSUE TITLE
Read OWL files to display names of classes in Pod frontend

### ISSUE THREAD

**Issue by srosset81** [activitypods/activitypods#129]
When we have the prefix, we can see if it is listed in LOV:

https://lov.linkeddata.es/dataset/lov/api/v2/vocabulary/info?vocab=foaf

Then we can look at the `versions` property, take the first one (the most recent one), and the OWL file will be in the `fileURL` property:

https://lov.linkeddata.es/dataset/lov/vocabs/foaf/versions/2014-01-14.n3

## Pending issues
- The LOV database doesn't include all vocabularies. ActivityStreams is missing (!)
- Submitting a vocabulary takes times and is subject to approval
- Almost all classes descriptions in OWL files are in English...
- Parsing the LOV results and the OWL files will take time, and must most likely be done on the frontend

## Alternatives
- Create our own database, listing OWL files and JSON-LD context

**Comment by srosset81** [comment]
Finally we will do it a bit differently, imitating the [AccessDescription](https://solid.github.io/data-interoperability-panel/specification/#access-descriptions) of Solid Application Interoperability.

```js
{
  "@type": "apods:ClassDescription",
  "apods:registeredClass": "https://www.w3.org/ns/activitystreams#Event",
  "skos:prefLabel": "Events"@en,
  "skos:definition": "Events people can meet at"@en,
  "apods:labelPredicate": "https://www.w3.org/ns/activitystreams#name",
}
```

The `apods:labelPredicate` will allow the frontend to display the title of resources in the ["My Data" tab](https://github.com/assemblee-virtuelle/activitypods/issues/188).

**Comment by srosset81** [comment]
Most of the work has been done here: #190

We still need a migration tool from v1

**Comment by renyuneyun** [comment]
> When we have the prefix, we can see if it is listed in LOV:
> 
> https://lov.linkeddata.es/dataset/lov/api/v2/vocabulary/info?vocab=foaf

This is different from my understanding of how Web ontology works. From my understanding, you should go back to the actual resource this prefix points to, from the heading section (of turtle, e.g.).

For example, you can have

```
@prefix foaf <http://xmlns.com/foaf/0.1/>.
@prefix : <http://example.org>.

:me a foaf:Person.
```

Then you need to download `http://xmlns.com/foaf/0.1/` as specified in the heading, which in turn is a valid owl file (maybe you need to explicitly specify the `Accept: application/rdf+xml` header or alike). Then you should parse this owl file to obtain the definitions.

> IIRC, some / many rdf.js libraries do **not** expose the prefixes. This is always a question from me. On the other hand, Python's rdflib seems to do a good job, IIRC.

This is decentralized. While relying on lov.linkeddata.es is centralized, and problematic, because the prefix name itself may be different -- I do not have to use `foaf` as the prefix name for foaf vocabulary. In fact, my experience with rdf.js libraries shows that many of them manipulate the prefixes arbitrarily.

Of course, we always need to deal with the issue of prefix being arbitrary, and sometime non-existent.

**Comment by srosset81** [comment]
@renyuneyun Unfortunately some ontologies don't have an OWL file, or the OWL file doesn't have a definition for all classes. And even when they have, there is never a translation in other language, which was a requirement for us (ActivityPods is being used by many french users).
